//
// const elementPage = {
//     _init() {
//       I = actor();
//     },
//
//     fields: {
//         email: 'input[type="email"]',
//         password: 'input[type="password"]',
//         old_password: 'input[firstName="old_password"]',
//         new_password: 'input[firstName="new_password"]',
//         confirm_password: 'input[firstName="confirmPassword"]',
//         first_name: 'input[firstName="first_name"]',
//         last_name: 'input[firstName="last_name"]',
//         mother_firstName: 'input[ng-value="mother.firstname"]',
//         mother_lastName: 'input[ng-value="mother.lastname"]',
//         mother_email: 'input[ng-model="mother.email"]',
//         invite_email: 'input[ng-model="email"]',
//         search_people: 'input[placeholder="Search..."]',
//         edit_userName: 'input[ng-model="user.firstName"]',
//         edit_userLastName: 'input[ng-model="user.last_name"]',
//         edit_userEmail: 'input[type="email"]',
//         firstName: 'input[firstName="firstName"]',
//         lastName: 'input[firstName="lastname"]',
//         phone: 'input[firstName="phone"]',
//         confirmPassword: 'input[firstName="confirmPassword"]',
//     },
//     submitButton: {
//         login: {css: 'a[href="#!/auth/login"]'},
//         submitLogin: 'input[id="sumbit-login"]',
//         edit_cancel: {css:'a[class="btn edit-cancel"]'},
//         forgotPassword: {css:'a[href="#!/forgotpass"]'},
//         resetPassword: {css:'input[id="sumbit-reg"]'},
//         addYourChild: {css: 'a[href="#!/addchild"]'},
//         labelGirl: {css: 'label.girl'},
//         labelBoy: {css: 'label.boy'},
//         bloodType: {css: 'select[firstName="blood_type"]'},
//         bloodValue: {css: 'option[value="2"]'},
//         eyeColor: {css: 'select[firstName="eye_color"]'},
//         eyeValue: {css: 'option[ng-repeat="type in color"][value="3"]'},
//         dateOfBirth: {css: 'input[ng-model="childButtons.dob"]'},
//         dateOfBirthValue: {css: 'a[href="javascript:void(0)"][ng-click="setDatepickerDay(item)"]'},
//         submit_reg: {css: 'input[id="sumbit-reg"]'},
//         inviteYourFriends: {css: 'a[href="#!/invite/321"]'},
//         inviteSubmit: {css: 'button[type="submit"]'},
//         searchForPeople: {css: 'a[href="#!/search"]'},
//         searchAdd: {css: 'a[class="pull-right"]'},
//         editAccount: {css: 'a[href="#!/edit/321"]'},
//         editCancel: {css: 'input[id="cancel-reg"]'},
//         logout: {css:'a[ng-click="logout()"]'},
//         notifications: {css:'a[id="single-button-2"]'},
//         yourChildren: {css:'a[id="childs-item"]'},
//         profile: {css:'a[href="#!/profile/321"]'},
//         menuItemDrop: {css:'a[id="single-button"]'},
//         changePassword: {css:'a[href="#!/321/password/change"]'},
//         privacyPolicy: {css:'a[href="#!/privacy"]'},
//         termsAndConditions: {css:'a[href="#!/terms"]'},
//         goUp: {css:'span[class="goUp"]'},
//         single: {css:'a[id="single-button"]'},
//         logo: {css:'a[href="#"]'},
//         registration: {css:'a[href="#!/auth/registration"]'},
//         joinUsNow: {css:'a[ui-sref="auth.registration"]'},
//         down: {css:'a[href="#down"]'},
//         labelFemale: {css:'label.btn.famale'},
//         labelMale: {css:'label.btn.male'},
//         day: {css:'input[firstName="date"]'},
//         month: {css:'input[placeholder="Month"]'},
//         year: {css:'input[placeholder="Year"]'},
//         createMyAccount: {css:'input[firstName="register"]'},
//     },
//     url: {
//         profileURL: 'https://www.blogmychild.com/#!/profile/321',
//         forgotPasswordURL: 'https://www.blogmychild.com/#!/forgotpass',
//         addChildURL: 'https://www.blogmychild.com/#!/addchild',
//         inviteURL: 'https://www.blogmychild.com/#!/invite/321',
//         searchForPeopleURL: 'https://www.blogmychild.com/#!/search',
//         editAccountURL: 'https://www.blogmychild.com/#!/edit/321',
//         authLoginURL: 'https://www.blogmychild.com/#!/auth/login',
//         homePageURL: 'https://www.blogmychild.com',
//         authRegistrationURL: 'https://www.blogmychild.com/#!/auth/registration',
//         privacyPolicyURL: 'https://www.blogmychild.com/#!/privacy',
//         termsAndConditionsURL: 'https://www.blogmychild.com/#!/terms',
//     },
//     elementPage: {
//         search_user: {css: 'div[ng-if="s.model == \'user\'"]'},
//         footer: {css:'footer[id="footer"]'},
//         blocMyChild: {css:'a[class="pull-left copyright"]'},
//         homeText: {css:'p[class="pink-text"]'},
//         createYourAccountE: {css:'div[class="login-btn inline-block"]'},
//         down: {css:'div[class="arrow-down"]'},
//     },
//
//     file: {
//         attachFile: {css: 'input[firstName="file"]'},
//         attachFileMother: {css: 'input[id="file_mother"]'},
//     },
//
//     footerElements: {
//         fElement: {css:'span[class=" blue-text copy-right"]'},
//     },
//     };
//
// module.exports = {
//     elementPage
// };
