module.exports = {


    fields: {
        email            : 'input[type="email"]',
        password         : 'input[type="password"]',
        old_password     : 'input[name="oldPassword"]',
        new_password     : 'input[name="password"]',
        repeat_password  : 'input[name="password2"]',
        first_name       : 'input[name="first-name"]',
        last_name        : 'input[name="last-name"]',
        invite_email     : 'input[name="email"]',
        search_people    : 'input[placeholder="Search..."]',
        edit_userName    : 'input[name="name"]',
        edit_userLastName: 'input[name="last_name"]',
        edit_userEmail   : 'input[name="email"]',
        firstName        : 'input[name="first-name"]',
        lastName         : 'input[name="last-name"]',
        phone            : 'input[firstName="phone"]',
        confirmPassword  : 'input[firstName="confirmPassword"]',
        enterCode1       : 'input[id="mat-input-3"]',
        enterCode2       : 'input[id="mat-input-4"]',
        enterCode3       : 'input[id="mat-input-5"]',
        enterCode4       : 'input[id="mat-input-6"]',
        deleteChildPopup : 'input[name="password"]',

    },

    submitButton: {
        login             : {css: 'a[href="/auth/login"]'},
        submitLogin       : 'button[type="submit"]',
        forgotPassword    : {css: 'a[href="/auth/forgot"]'},
        resetPassword     : {css: 'button[type="submit"]'},
        addYourChild      : {css: 'a[href="/create-child"'},
        labelGirl         : {css: 'div.box.female'},
        labelBoy          : {css: 'div.box.male'},
        labelNotborn      : {css: 'div.box'},
        bloodType         : {css: 'select[firstName="blood_type"]'},
        bloodValue        : {css: 'option[value="2"]'},
        eyeColor          : {css: 'select[firstName="eye_color"]'},
        eyeValue          : {css: 'option[ng-repeat="type in color"][value="3"]'},
        dateOfBirth       : {css: 'input[ng-model="childButtons.dob"]'},
        dateOfBirthValue  : {css: 'a[href="javascript:void(0)"][ng-click="setDatepickerDay(item)"]'},
        submit_reg        : {css: 'input[id="sumbit-reg"]'},
        inviteYourFriends : {css: 'a[href="/user/invite"]'},
        inviteByEmail     : {css: 'a[href="/user/invite/email"]'},
        inviteByPhone     : {css: 'a[href="/user/invite/phone"]'},
        inviteSubmit      : {css: 'button[type="submit"]'},
        searchForPeople   : {css: 'a[href="/user/search"]'},
        searchAdd         : {css: 'a[class="pull-right"]'},
        logout            : {css: 'a.mat-menu-item'},
        notifications     : {css: 'button.bmc-grey.icon.mat-flat-button'},
        yourChildren      : {css: 'button.bmc-grey.icon.mat-flat-button'},
        profile           : {css: 'a[href="/user/587"]'},
        menuItemDrop      : {css: 'a[id="single-button"]'},
        changePassword    : {css: 'a[href="/user/profile/change-password"]'},
        goUp              : {css: 'span[class="goUp"]'},
        day               : {css: 'input[firstName="date"]'},
        month             : {css: 'input[placeholder="Month"]'},
        year              : {css: 'input[placeholder="Year"]'},
        single            : {css: '/html/body/app-root/div/app-header/header/div/div/div[2]/button[3]'},
        logo              : {css: 'a[href="#"]'},
        registration      : {css: 'a[href="/auth/register"]'},
        joinUsNow         : {css: 'a[ui-sref="auth.registration"]'},
        down              : {css: 'a[href="#down"]'},
        privacyPolicy     : {css: 'a[href="/"]'},
        termsAndConditions: {css: 'a[href="/"]'},
        labelFemale       : {css: 'div.box.female'},
        labelMale         : {css: 'div.box.male'},
        createMyAccount   : {css: 'input[firstName="register"]'},
        editAccount       : {css: 'a.mat-menu-item'},
        googlePlay        : {css: 'a[href="https://play.google.com/store/apps/details?id=com.syneweb.blogmychild&hl=en"]'},
        appStore          : {css: 'a[href="https://itunes.apple.com/us/app/blogmychild/id1265063273?mt=8"]'},
        next              : {css: '/html/body/app-root/div/div/app-create-child/div/div/div/div/form/div/div/div[2]/div[2]/button'},
        nextSecond        : {css: '/html/body/app-root/div/div/app-auth/div/div/div/app-register/div/form/div/div/div[2]/div[2]/button'},
        nextThird         : {css: '.row > .col:last-child button'},
        goChildProfile    : {css: 'a[class="bmc-gradient fluid mat-flat-button"]'},
        editChild         : {css: 'div[class="settings ng-star-inserted"]'},
        deleteChild       : {css: 'button[class="mat-menu-item ng-star-inserted"]'},
        deleteChildApprove: {css: 'button[class="mat-flat-button mat-warn"]'},
        deleteProfile     : {css: 'a[href="/user/profile/delete"]'},

    },

    url: {
        profileURL           : 'http://new.bmc.hibridmena.com/user/587',
        forgotPasswordURL    : 'http://new.bmc.hibridmena.com/auth/forgot',
        addChildURL          : 'http://new.bmc.hibridmena.com/create-child',
        inviteEmailURL       : 'http://new.bmc.hibridmena.com/user/invite/email',
        invitePhoneURL       : 'http://new.bmc.hibridmena.com/user/invite/phone',
        searchForPeopleURL   : 'http://new.bmc.hibridmena.com/user/search',
        editAccountURL       : 'http://new.bmc.hibridmena.com/user/profile',
        authLoginURL         : 'http://new.bmc.hibridmena.com/auth/login',
        homePageURL          : 'http://new.bmc.hibridmena.com/',
        privacyPolicyURL     : 'https://www.blogmychild.com/#!/privacy',
        termsAndConditionsURL: 'https://www.blogmychild.com/#!/terms',
        authRegistrationURL  : 'http://new.bmc.hibridmena.com/auth/register',
        googlePlayURL        : 'https://play.google.com/store/apps/details?id=com.syneweb.blogmychild&hl=en',
        appStoreURL          : 'https://itunes.apple.com/us/app/blogmychild/id1265063273?mt=8',
        createChildUrl       : 'http://new.bmc.hibridmena.com/child/',
        changePasswordURL    : 'http://new.bmc.hibridmena.com/user/profile/change-password',
        deleteProfileURL     : 'http://new.bmc.hibridmena.com/user/profile/delete',
    },

    elementPage: {
        search_user           : {css: 'div[ng-if="s.model == \'user\'"]'},
        footer                : {css: 'footer.footer'},
        blocMyChild           : {css: 'div[class="col-auto copyrights"]'},
        createYourAccountE    : {css: 'div[class="login-btn inline-block"]'},
        homeText              : {css: 'h1'},
        createYourAccountLogin: {css: 'div[class="col-sm-auto hide xs"]'},
        down                  : {css: 'div[class="arrow-down"]'},
        congratulations       : {css: 'div[class="step congratulations ng-star-inserted"]'},

    },

    childButtons: {
        childId500     : {css: 'a[href="/child/1621"]'},
        editChild      : {css: 'i[class="fa fa-cog editChild"]'},
        editChildId    : {css: 'a[href="#!/children/500"]'},
        deleteChildId  : {css: 'a[class="forPopoverMenu"]'},
        article        : {css: 'a[class="nav-link"]'},
        addAMemory     : {css: 'div.addFeedButton.ng-star-inserted'},
        addPost        : '/html/body/app-root/div/div/app-child/div/div/div[2]/div/app-feeds/div[2]/div[2]/div[1]/div',
        savePost       : {css: 'button[type="submit"]'},
        deletePost     : {css: 'div[class="open-tools ng-star-inserted"]'},
        deletePostProve: {css: 'button[class=mat-menu-item]'},
    },

    childFields: {
        title      : {css: 'input[name="title"]'},
        description: {css: 'textarea[formcontrolname="description"]'},
    },

    file: {
        attachFile      : {css: 'input[id="avatar-input"]'},
        attachFileMother: {css: 'input[id="file_mother"]'},

    },

    footerElements: {
        fElement: {css: 'div[class="row align-items-center justify-content-between"]'},
    },

    root: {
        startDate: {css: 'input[ng-model="childButtons.dob"]'},
        date     : '01-02-2019',
    },

}
